apiVersion: v1
kind: Secret
type: Opaque
data:
  {{- $mysql_user := default (randAlphaNum 8) .Values.mysql.user }}
  {{- $mysql_password := default (randAlphaNum 16) .Values.mysql.password }}
  {{- $mysql_root_password := default (randAlphaNum 16) .Values.mysql.rootPassword }}
  mysql-user: {{ $mysql_user | b64enc | quote }}
  mysql-password: {{ $mysql_password | b64enc | quote }}
  mysql-root-password: {{ $mysql_root_password | b64enc | quote }}
  binding: {{ cat `{"uri":"mysql://` $mysql_user `:` $mysql_password `@` .Values.mysql.service.name `:` .Values.mysql.service.externalPort `/` .Values.mysql.dbname `" }` | nospace | b64enc }}
metadata:
  name: {{ .Values.mysql.binding.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: bluecompute
    micro: orders
    tier: data 
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"

